### ISSUE TITLE
Breaking changes with firebase npm package v8

### ISSUE THREAD

**Issue by subwaymatch** [nandorojo/swr-firestore#66] opened 2020-11-22 17:35 UTC
Thank you for a great package. 🙏 This package makes my life much easier when dealing with Firestore. This is just a small heads-up for your next release.

Framework: Next.js 10
swr-firestore version: 0.16.0

I was in the process of updating all npm packages in my project but noticed that `swr-firestore` throws an error when `firebase` > v`8.0.0` is installed. I've downgraded `firebase` back to `7.x.x`. This is not a _real_ issue since using an older version of the `firebase` package works perfectly fine. According to Firebase JS SDK's release notes, `firebase` package v`8.0.0` contains [breaking changes](https://firebase.google.com/support/release-notes/js#version_800_-_october_26_2020).  

![image](https://user-images.githubusercontent.com/1064036/99910806-bd34f800-2cb5-11eb-9bf4-2ca584ff9a85.png)

**Comment by nandorojo** [comment] 2020-11-22 17:41
Hey, thanks for the issue!

This is a duplicate of #58. You can see my solution [here](https://github.com/nandorojo/swr-firestore/issues/59#issuecomment-719950071).

**Closed by nandorojo** 2020-11-22 17:41 UTC

**Comment by subwaymatch** [comment] 2020-11-22 17:44
Should have searched through the issues first 🙄. Thanks!
