### ISSUE TITLE
where clause doesn't use correct type when returning data if property is nested

### ISSUE THREAD

**Issue by mjbates7** [nandorojo/swr-firestore#61] opened 2020-10-30 15:01 UTC
Hello, when using a where clause in which you specify a nested property, it makes the data variable that is returned not map to the type that you've specified. 

See below screenshot:

![image](https://user-images.githubusercontent.com/4522738/97719809-6d508000-1abf-11eb-8fe5-7716de1d1c9b.png)

I would expect to see those properties, plus the properties from the type that I pass in.

Any ideas on this? Possibly related to #53

**Comment by nandorojo** [comment] 2020-10-31 01:08
Seems like an effective duplicate of #53. What if you `@ts-ignore` above where, does that do anything?

**Comment by nandorojo** [comment] 2020-10-31 15:34
Fixed in `0.16.0`

**Closed by nandorojo** 2020-10-31 15:34 UTC
